### ISSUE TITLE
Rework name

### ISSUE THREAD

**Issue by bernardd** [matehat/cqerl#103]
Hey @matehat - I've been working on a rearchitecting/simplification of the cqerl frontend. In a nutshell, I've stripped out most of the "old" stuff (proplists value sets, pooler support, support for old versions of Erlang etc). The ultimate goal, however, was the addition of Token Aware Policy support. TAP didn't really fit with the existing API, hence the rework. It's still got some cleanup and testing work to be done, but the fundamentals are there and, as far as I can tell right now, working. You can take a look at https://github.com/hippware/cqerl/tree/rework.
I don't imagine this being merged into cqerl, not least because it breaks backwards compatibility in almost every way, so my question is how you'd like me to handle naming it. I don't want to imply that it's anything other than a fork of your substantial work (and at a minimum I'll have a prominent note in the README to that effect), but nor do I want to cause confusion for people by having multiple incompatible things all called cqerl (or some small variation thereof).

With that in mind, the obvious options are either
* Something like `cqerl2` (a la rebar3), or
* A completely different name (which I'm yet to think of)

If it was just my work, I'd obviously go for the second option but since the bulk is still basically your original work, I'd rather have your opinion first :)

**Comment by matehat** [comment]
Thanks @bernardd 

Can you explain a bit more about the break of compatibility? I wonder if there couldn't be a migration path between the two that would make it possible for the next version of cqerl to be what you have there, plus a backward-compatible API that prevents existing dependent projects from changing too much of their code.

**Comment by bernardd** [comment]
Sure. The high level changes are:
* `cqerl:get_client` and `cqerl:close_client` calls are no longer required. Instead, client groups (pools) are defined either in the app config or at runtime using `cqerl:add_group`. Clients are then either selected automatically (using token-aware-policy), randomly selected using the existing hash algorithm (if TAP is disabled or fails to provide a client) or selected from an explicitly named group using `cqerl:[run|send]_query_named`.
* Along with the above, client's are now keyed off only the host and keyspace rather than all the configuration options. Specially configured client groups can still be set up by using named groups, but I figured it would be a fairly unusual case that warranted multiple sets of clients with the same node and keyspace but different opts.
* Query values and returns are now maps only (removing proplist support)
* We now use rebar3 for building

Much smaller, but still compatibility breaking changes
* Async queries now tag their replies with `cqerl_result` rather than `result`
* `no_more_result` is now `no_more_results`

I think that's basically all the compatibility breaking changes.

In principle, I can't think of any reason that a compatibility layer couldn't be implemented. The main caveat is that this version won't compile on anything earlier than 18.3 (due to the previously missing `gen_tcp:socket()` type) and even with a minor tweak to workaround that, it definitely won't run on a version that doesn't have map support. The motivation for that was purely selfish - we're working with 19.0 now, so stripping out legacy stuff made making the other changes easier.

**Comment by matehat** [comment]
Thanks for the write up!

I think it's definitely going in the right direction. So what do you think of the possibility of pushing these changes in a 2.0 branch, which would allow anyone to start using it by being explicit in the branch name, while we're stabilizing code, and when we're ready, make that the main branch, allowing legacy clients to use the 1.0 branch?

**Comment by bernardd** [comment]
Yeah, that's fine with me. I'll make the branch and push over what I've got so far.

**Comment by bernardd** [comment]
Work in progress is now in v2.0-pre branch. I'll keep it updated with fixes and improvements as I go.

**Comment by matehat** [comment]
Thanks!
