### ISSUE TITLE
batch query timeout

### ISSUE THREAD

**Issue by lealoureiro** [matehat/cqerl#107]
Hi all,

I'm trying to run a batched query with a few DELETE statements and i'm getting a timeout end using other normal queries it works fine. I'm using cqerl 0.9.0 tag and Apache Cassandra 2.2.5. Please find below the piece of code:

```
delete_transaction(AccountId, TransactionId) ->
  case cqerl:new_client() of
    {ok, Client} ->
      Result = cqerl:run_query(Client, #cql_query_batch{mode = logged, queries = [
        #cql_query{statement = <<"DELETE FROM transactions WHERE account_id = ? AND transaction_id = ?">>, values = [{account_id, AccountId}, {transaction_id, TransactionId}]},
        #cql_query{statement = <<"DELETE FROM tags_by_transaction WHERE transaction_id = ? ">>, values = [{transaction_id, TransactionId}]},
        #cql_query{statement = <<"DELETE FROM transactions_by_tag WHERE transaction_id = ? ">>, values = [{transaction_id, TransactionId}]},
        #cql_query{statement = <<"DELETE FROM transactions_by_external WHERE transaction_id = ? ">>, values = [{transaction_id, TransactionId}]}
      ]}),
      cqerl:close_client(Client),
      case Result of
        {ok, void} ->
          true;
        _ ->
          false
      end;
    _ ->
      system_error
  end.
```
Also tried with unlogged mode. 

Am I doing something wrong? 

Thanks in advance!

**Comment by matehat** [comment]
At first glance, I don't see anything obvious. Have you tried running the exact same commands using cqlsh? http://docs.datastax.com/en/cql/3.1/cql/cql_reference/batch_r.html

**Comment by lealoureiro** [comment]
Some queries were wrong... i need to fix it.

What is faster, perform them separately or in batch like in example above (unlogged)? 

Thanks.

**Comment by bernardd** [comment]
Generally, don't use batches to improve performance - they're meant for maintaining consistency between tables. See http://docs.datastax.com/en/cql/3.1/cql/cql_using/useBatch.html

**Comment by lealoureiro** [comment]
Oh got it. understood now. Thanks all for help. I will close the issue.
