### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by hopewise** [matehat/cqerl#108]
I have just installed Cassandra 3.7, I tried elixir cqerl to connect:

    {:ok, client} = :cqerl.new_client({{x,x,x,x},9042},[{:auth, {:cqerl_auth_plain_handler, [{"user_name", "password"}]}}])

but I got this error:

> ** (exit) exited in: :gen_server.call(:cqerl, {:get_client, {{x,x,x,x}, 9042}, [auth: {:cqerl_auth_plain_handler, [{"user_name", "password"}]}]})
>     ** (EXIT) time out
>     (stdlib) gen_server.erl:204: :gen_server.call/2

Any advice?

**Comment by bernardd** [comment]
Can you connect to the node using
`cqlsh -u user_name -p password x.x.x.x 9042`
?

**Comment by matehat** [comment]
@hopewise re-open if you still experience the issue and you think there's something wrong
