### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by m4mark** [matehat/cqerl#116]
I'm using the library in an Elixir project and received the following error after trying to connect... Another project using an earlier version of the library uses the same statement without issue.

iex(1)> {:ok, client} = :cqerl.get_client()
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:cqerl_clusters, :"$primary_cluster")
             src/cqerl_cluster.erl:52: :cqerl_cluster.get_any_client/1

**Comment by bernardd** [comment]
Is the app running?

**Comment by m4mark** [comment]
Yes the app is running...

**Comment by bernardd** [comment]
I ask because getting that error implies that the ets table doesn't exist. And that table is set up at app startup. So either the call is being made before cqerl is started, or somehow the cqerl_clusters table is being deleted.

**Comment by bernardd** [comment]
At least, those are the only two options that seem likely (and really only the first one seems especially likely). Can you double check by running `:application.which_applications()` from the shell?

**Comment by m4mark** [comment]
Admittedly I've created an umbrella project but at the same time specified cqerl in the main mix.exs and the configuration options to go along with it.

  def application do
    [applications: [:vex, :cqerl, :logger]]
  end

**Comment by m4mark** [comment]
I cannot see the cqerl library appearing in the list, only the sub modules I created.

iex(1)> :application.which_applications()
[{:dao, 'dao', '0.1.0'}, {:unicorn, 'unicorn', '0.1.0'},
 {:search, 'search', '0.1.0'}, {:horse, 'horse', '0.1.0'},
 {:donkey, 'donkey', '0.1.0'}, {:insight, 'insight', '0.1.0'},
 {:zebra, 'zebra', '0.1.0'}, {:logger, 'logger', '1.3.2'},
 {:hex, 'hex', '0.13.0'}, {:inets, 'INETS  CXC 138 49', '6.3.1'},
 {:ssl, 'Erlang/OTP SSL application', '8.0'},
 {:public_key, 'Public key infrastructure', '1.2'},
 {:asn1, 'The Erlang ASN1 compiler version 4.0.3', '4.0.3'},
 {:crypto, 'CRYPTO', '3.7'}, {:mix, 'mix', '1.3.2'}, {:iex, 'iex', '1.3.2'},
 {:elixir, 'elixir', '1.3.2'}, {:compiler, 'ERTS  CXC 138 10', '7.0.1'},
 {:stdlib, 'ERTS  CXC 138 10', '3.0.1'}, {:kernel, 'ERTS  CXC 138 10', '5.0'}]

**Comment by bernardd** [comment]
So the app's not in fact running, and neither is `vex` by the look of it. Which means your problem is not with cqerl, but with your use of mix.

**Comment by m4mark** [comment]
I think i agree, cqerl is listed among the apps when running :application.which_applications() in my more standard project. I'll backtrack and see what I can come up with.

iex(1)> :application.which_applications()
[{:hippo, 'hippo', '0.1.0'}, {:logger, 'logger', '1.3.2'},
 {:cqerl, 'CQErl client for Cassandra', '1.0.1'},
 {:uuid, 'Native UUID Generation', '1.4.1'},
 {:quickrand, 'Quick Random Number Generation', '1.4.0'}, {:lz4, [], '0.2.2'},
 {:snappy, 'snappy compressor/decompressor Erlang NIF wrapper', '1.1.1'},
 {:semver, 'Semantic Versioning Support Library', '0.0.1'},
 {:re2, 'Erlang NIF bindings for the re2 regex library', '1.4.0'},
 {:pooler, [], '1.5.0'}, {:vex, 'vex', '0.5.5'}, {:hex, 'hex', '0.13.0'},
 {:inets, 'INETS  CXC 138 49', '6.3.1'},
 {:ssl, 'Erlang/OTP SSL application', '8.0'},
 {:public_key, 'Public key infrastructure', '1.2'},
 {:asn1, 'The Erlang ASN1 compiler version 4.0.3', '4.0.3'},
 {:crypto, 'CRYPTO', '3.7'}, {:mix, 'mix', '1.3.2'}, {:iex, 'iex', '1.3.2'},
 {:elixir, 'elixir', '1.3.2'}, {:compiler, 'ERTS  CXC 138 10', '7.0.1'},
 {:stdlib, 'ERTS  CXC 138 10', '3.0.1'}, {:kernel, 'ERTS  CXC 138 10', '5.0'}]

Many thanks for your help.

**Comment by bernardd** [comment]
No worries - good luck.
