### ISSUE TITLE
how to use protocol version with clusters?

### ISSUE THREAD

**Issue by BlueHotDog** [matehat/cqerl#118]
Seems like i'm missing something :(
i'm doing this in elixir:
```elixir
config :cqerl,
  cassandra_clusters: [
    cluster1: { ["10.0.0.1:9042"], [
      keyspace: "some_keyspace",
    ]}
  ],
  protocol_version: 3,
  maps: true,
  text_uuids: true
```

but this doesnt seems to work :(

**Comment by matehat** [comment]
Which part isn't working and how is it not working?

**Comment by BlueHotDog** [comment]
nm, managed to figure it out

**Comment by matehat** [comment]
ok, thanks. Feel free to say what happened so the next person knows how to solve a problem similar to the one you had.
