### ISSUE TITLE
cluster not configured

### ISSUE THREAD

**Issue by sabondano** [matehat/cqerl#120]
How can I troubleshoot this error?
`{:error, :cluster_not_configured}`

I'm getting it when running `:cqerl.get_client()`

Cassandra seems to be running fine when I run cqlsh. Not sure what could be the issue here. Any tips/suggestions?

**Comment by matehat** [comment]
Do you have nodes configured in your [system configuration][1]? 

[1]: https://github.com/matehat/cqerl#using-environment-variables

**Comment by sabondano** [comment]
Thank you Mathieu. I ended up figuring my issue out and it had nothing to do with cqerl :). By mistake, while getting cassandra installed/started, I had two installations in my machine and that was throwing things off. Closing this one. Thank you for all your hard work on cqerl and for sharing it!

**Comment by matehat** [comment]
Thanks for reporting issues! 😄
