### ISSUE TITLE
main app won't compile after adding cqerl to dependency list

### ISSUE THREAD

**Issue by mousavian** [matehat/cqerl#121]
_Notice: Newbie here._

I have initiated a new app using Erlang/OTP 18 and Rebar3 on Ubuntu server 16.04.

On first compile, it works fine but it seems Rebar3 is not compiling the main module/app as soon as I add cqerl to its dependencies list.

(this directory doesn't exists after update rebar.config and compile again `_build/default/lib/APP_NAME`)

Is this a known issue or I'm missing something here? :)

**Comment by matehat** [comment]
Is there any error printed out?

**Comment by mousavian** [comment]
@matehat No, that's why I don't know which part is broken.
It runs successfully without error when I have an application (`rebar3 new app APP_NAME`),
but throw 
`{"init terminating in do_boot",{undef,[{MY_APP,my_function_name,[],[]},{init,start_it,1,[]},{init,start_│
em,1,[]}]}}` 
when I have a library (`rebar3 new lib APP_NAME`) by running `erl -env ERL_LIBS _build/default/lib -s APP_NAME my_function_name -noshell`.

Ps1: I have already used `-compile(export_all).` to export all of functions and it works fine before adding cqerl to the deps.

Ps2: In case it might be helpful, for the first time it was downloading and compiling cqerl, it gave me an error that re2.h file doesn't exist. I tried to install re2 using google's repo and it solved the problem.

**Comment by janajri** [comment]
@mousavian how did you end up resolving this issue. I'm seeing something similar on my end.

**Comment by mousavian** [comment]
@janajri  I don't really remember how i solved it or even it solved or not; but just can say our requirements changed and cassandra was no longer needed. So we are not using this lib anymore.
