### ISSUE TITLE
Query fails when ttl is specified

### ISSUE THREAD

**Issue by aShobhitSingh** [matehat/cqerl#122]
statement = "INSERT INTO data(scope)
         VALUES(?) USING ttl ?",
    values = [{scope, "Scope Value"},{[ttl], 3650}]

This does not work on master branch. Fails with no match of right hand value {error,{throw,{{missing_parameter,{parameter,'[ttl]'},

**Comment by bernardd** [comment]
That's because you haven't made `[ttl]` an atom. It should be `'[ttl]'`.

**Comment by aShobhitSingh** [comment]
Thanks, it works. This wasn't documented.

**Comment by bernardd** [comment]
I agree the documentation could stand to be phrased slightly less ambiguously. Please feel free to submit an improvement :)

**Comment by aShobhitSingh** [comment]
Sure :)

**Comment by matehat** [comment]
I just changed that a bit in f29654fea3aba43db214de03469cfc30de00c870
