### ISSUE TITLE
Even if one node of the cluster is down, cqerl tries to reach it

### ISSUE THREAD

**Issue by unbalancedparentheses** [matehat/cqerl#136]
After detecting one of the cassandra cluster node is down, it should not try to connect to it again for some time. It should get tagged as a down node for a while. 

There should be some type of load balancing at the client level. Using a cassandra cluster with a client that does not have load balancing is worst than connecting to a single cassandra instance.

**Comment by unbalancedparentheses** [comment]
@matehat do you have any comments about this?

**Comment by PiedPieper** [comment]
@unbalancedparentheses Your issue is that - you have a list of nodes in your config, you try perform a query and it fails on one node. Maybe, if a transaction is performed on one node and it fails, cqerl should try the other nodes in the list until it succeeds and marks the other node as down for "X" amount of time. Would that solve your problem?

**Comment by vanjabucic** [comment]
Looks like the driver is just getting a random node from a list of nodes (`lists:nth(rand:uniform(length(Nodes)), Nodes)`)
Some consideration has to be given to the health of a node (see java DBCP testOnBorrow for example).
Cassandra nodes go down as part of a scheduled maintenance, or node failures, and in either case it is assumed that the client should not be affected by those. That is why people use a cluster of servers, for HA.
Here we have clients getting a storm of failures if a single node is down, like these:
```
11:15:17.217 [error] Ranch protocol #PID<0.29215.4269> of listener apiservice.Router.HTTP (cowboy_protocol) terminated
** (exit) an exception was raised:
    ** (CQEx.Error) {:shutdown, {:failed_to_start_child, 
                                                     {:cqerl_client, {{{10, 0, 0, 41}, 9042}, [cass_clusters: [prod: {[{"10.0.0.42", 9042}, {"10.0.0.43", 9042}, {"10.0.0.41", 9042}], [keyspace: "ks"]}, 
                                                                                                               dev:  {[{"10.0.0.22", 9042}], [keyspace: "ks"]}], included_applications: [], keyspace: :ks]}, 1}, 
                                                                     {:connection_error, :econnrefused}}}
        (cqex) lib/cqex/client.ex:18: CQEx.Client.new!/1
```
Kind of defeats the purpose if a scheduled maintenance of a single node messes up the whole upstream operation.

Additionally, the size of ETS tables grows and grows during this period of errors (failed connection references I assume), and it never recovers the original memory footprint. 
ETS tables should be purged of stale references. Not sure if that warrants another issue.

**Comment by matehat** [comment]
Sorry for the long delay, was out heads down on some other project. Do you guys have any idea on the expected behavior with this? Keep some state to track the `down` status of some nodes, and have a exponential backoff retry mechanism?

**Comment by matehat** [comment]
I've a experimental branch for this on #157, can you @vanjabucic and @unbalancedparentheses try it out and see if it works?

I'm now basically tracking down when nodes reply with `econnrefused` and wait for a time, and that time grows the more failure we get.

**Comment by matehat** [comment]
The branch is in, I think it does what you guys were asking. Thanks for posting!
