### ISSUE TITLE
Can't compile UUID - call to crypto:rand_bytes/1 will fail

### ISSUE THREAD

**Issue by murphyryan1** [matehat/cqerl#145]
Having trouble compiling with cqerl in elixir.  It is pulling in a UUID library that is failing to compile.  The message was 

`call to crypto:rand_bytes/1 will fail`. 
`** (Mix) Could not compile dependency :uuid, "user/.mix/rebar3 bare compile --paths "/user/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile uuid", update it with "mix deps.update uuid" or clean it with "mix deps.clean uuid"`

Managed to fix the problem by using:
			`{:uuid, github: "okeuday/uuid", tag: "v1.7.2", override: true}`

Not sure if you need to do the same or not, or if there was another issue, but thought I'd let you know.

**Comment by matehat** [comment]
Should be fixed with the new dependency list
