### ISSUE TITLE
NXDomain Error When Providing Multiple Node IP Addresses

### ISSUE THREAD

**Issue by adamlongs1983** [matehat/cqerl#152]
I've been using your cqerl client in a Elixir project and I have been running into an issue with an NXDOMAIN error when connecting to a cluster.

I am using the add_nodes method to configure the nodes.

`:cqerl_cluster.add_nodes(["10.0.0.1", "10.0.0.2"], [{:auth, {:cqerl_auth_plain_handler, [{"USERNAME", "PASSWORD"}]}}])`

When I call get_client, I am getting the following crash report

`
=SUPERVISOR REPORT==== 21-Sep-2018::18:28:20 ===
    Supervisor: {<0.1203.0>,cqerl_client_sup}
    Context:    start_error
    Reason:     {connection_error,nxdomain}
    Offender:   [{pid,undefined},
                 {id,{cqerl_client,
                         {{"10.0.0.1,10.0.0.2",9042},
                          [{auth_hash,82978398},{keyspace,undefined}]},
                         1}},
                 {mfargs,
                     {cqerl_client,start_link,
                         [{"10.0.0.1,10.0.0.2",9042},
                          [{ssl,false},{keyspace,undefined}],
                          #Fun<cqerl.5.61185206>,
                          {{"10.0.0.1,10.0.0.2",9042},
                           [{auth_hash,82978398},{keyspace,undefined}]}]}},
                 {restart_type,permanent},
                 {shutdown,5000},
                 {child_type,worker}]
`

It seems your code is taking the two IP addresses I am providing, joining them and then providing them to `gen_tcp:connect` as a single address. This leads it to conclude it is a host name, not an IP address, due to the comma, thus leading to a NXDOMAIN when it can't find it on the DNS server.

Can you advise me on how to properly configure my cluster?

**Comment by matehat** [comment]
If you add nodes in the form:

`:cqerl_cluster.add_nodes([{10, 0, 0, 1}, {10, 0, 0, 2}], [{:auth, {:cqerl_auth_plain_handler, [{"USERNAME", "PASSWORD"}]}}]).`

It should just work.
