### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by silviucpp** [matehat/cqerl#154]
Hello,

I'm wonder if this project is still alive .. On OTP 21 after I get lot of warnings it's failing to compile:

===> Found no source files for:
"c_src/re2_nif.cc"
===> Missing artifact priv/re2_nif.so

Kind regards,
Silviu

**Comment by bernardd** [comment]
Hi @silviucpp - I can't speak for @matehat, but unfortunately I don't really do any work on it any more on account of not using Cassandra any more.

**Comment by matehat** [comment]
It’s not dead, but I’ve been mostly busy on other stuff. I’m happy to review PRs and try to fix urgent issues. This one seems like a dependency breaking on OTP 21, is it?

**Comment by silviucpp** [comment]
Hello @matehat perhaps yes.. Idea is that the deps were not updated for a while and now with OTP 21 almost everyone did releases to remove the erlang:getstacktrace calls and whatever else functions were removed or deprecated. 

Silviu

**Comment by matehat** [comment]
Hi again, I've fixed the issue reported in https://github.com/matehat/cqerl/commit/9e00f7a2c91120a6c5b8524a97a2b1b6505f56d7, so you should be good to go.
