### ISSUE TITLE
Update re2 to 1.9.1

### ISSUE THREAD

**Issue by wdavies973** [matehat/cqerl#158]
I've recently be corresponding with the `re2` dev to fix compile issues on Windows (https://github.com/dukesoferl/re2/issues/37). 

CQerl compilation fails on Windows because the `re2` compile fails. However this was recently fixed in `1.9.1`, so I would appreciate an update to `1.9.1` for `re2` (https://github.com/dukesoferl/re2/releases/tag/v1.9.1)

**Comment by matehat** [comment]
Done in #159. Thanks for reporting!
