### ISSUE TITLE
gen_fsm timeouts

### ISSUE THREAD

**Issue by d0rc** [matehat/cqerl#30]
https://github.com/d0rc/cqerl/commit/1c17e773c8bd4a5bf11033d2eb365bd2c3e9de0b - this what I had to do it keep it from failing again and again.
If you want, I can add corresponding option to application env, like `default_timeout`

**Comment by matehat** [comment]
Now, the default timeout value is 30 seconds, and a `query_timeout` environment variable can be provided to the `cqerl` application to change this.
