### ISSUE TITLE
About Cluster Support for Cassandra

### ISSUE THREAD

**Issue by hilarycheng** [matehat/cqerl#44]
Is cqerl supports for Cluster of Cassandra ? like the go cassandra driver https://github.com/gocql/gocql , that means if one cassandra goes down, the driver will connect to another hosts to do the database operation.

**Comment by matehat** [comment]
I'm currently working on cluster support, with support for token-aware policy (#48) among other things. Stay tuned!

**Comment by matehat** [comment]
The driver supports the scenario of the query raising an error, which you can catch on your side and re-run after getting a hold of another client. So basically, tools are in place to allow the user of the library to deal with that sort of issue properly.
