### ISSUE TITLE
Provide Elixir code samples

### ISSUE THREAD

**Issue by jacek99** [matehat/cqerl#45]
It would be great if all the code samples could be translated to Elixir,
 as well to make it easier for Elixir newbies to start using it (as many of us are unfamiliar with the original Erlang syntax and sometimes stumble trying to convert it).

Thank you, much appreciated

**Comment by matehat** [comment]
Thanks for this suggestion! I think I'll even go further and do a Elixir-specific library as an exercise to learn Elixir better :) Stay tuned

**Comment by Linicks** [comment]
That would be awesome!  I'm also an Elixir user that would like to use Cassandra.  I think as people discover Elixir, there will more and more demand for drivers etc. which will hopefully help projects like this.

**Comment by krakatoa** [comment]
If nobody's doing this, I would love to write some examples :+1:

**Comment by matehat** [comment]
@krakatoa Please do! I'll be more than happy to merge that!

**Comment by hayesgm** [comment]
Here's an example from my app:

```elixir
require Record
Record.defrecord :cql_query, statement: nil, values: [], reusable: :undefined, named: false, page_size: 100, page_state: :undefined, consistency: 1, serial_consistency: :undefined, value_encode_handler: :undefined

query = cql_query(
  statement: """
    SELECT *
    FROM users
    WHERE user_uuid = :user_uuid
  """,
  values: [
    user_uuid: UUID.string_to_binary!(user_uuid)
  ]
)
```

It took some effort to get that right it would be great to have examples in the wiki/repo.  Also, would we be receptive to adding a `package.exs` to get this project up on [hex.pm](http://hex.pm)?

**Comment by upbit** [comment]
@hayesgm I prefer extract record from cqerl.hrl:

~~~elixir
defmodule Cqerl.Utils do
  require Record
  Record.defrecord :cql_query, Record.extract(:cql_query, from: "deps/cqerl/include/cqerl.hrl")
  Record.defrecord :cql_query_batch, Record.extract(:cql_query_batch, from: "deps/cqerl/include/cqerl.hrl")
end
~~~

Config for `{:ok, client} = :cqerl.new_client()`:

~~~elixir
config :cqerl,
  cassandra_nodes: [{'127.0.0.1', 9042}],
  keyspace: "development"
~~~

Usage:

~~~elixir
  import Cqerl.Utils

  # Batch insert example:
  def add_populars(client, pairs) do
    query = cql_query(statement: "INSERT INTO user.populars (uid, ts, data) VALUES (?, ?, ?);")
    queries = for {uid, ts, data_map} <- pairs, do: cql_query(query, values: [uid: uid, ts: ts, data: Poison.encode!(data_map)])
    batch_query = cql_query_batch(mode: 0, consistency: 1, queries: queries)
    :cqerl.run_query(client, batch_query)
  end
~~~

**Comment by matehat** [comment]
Just created this project: https://github.com/matehat/cqex

**Comment by matehat** [comment]
That project wraps cqerl behind a Elixir-style interface, with Enumerable support, chaining and some custom structs. If you just wanted access to cqerl records though, it would be as simple as:

```elixir
iex(1)> import CQEx
iex(2)> cql_query(statement: "SELECT * FROM users;")
{:cql_query, "SELECT * FROM users;", [], :undefined, false, 100, :undefined, 1, :undefined,
 :undefined}
```
