### ISSUE TITLE
Doesn't seem to scale...

### ISSUE THREAD

**Issue by lpgauth** [matehat/cqerl#49]
Hi, I tried really hard to use your client... I didn't feel like writing a new one, but it just doesn't scale to my needs. I found at least 3 bottlenecks aka single process doing work for all queries. 

Here's an example of high load on your client:

    (rtb-gateway@h101)5> process_info(whereis(cqerl), message_queue_len).
    {message_queue_len,383675}

Obviously the gen_server times out and I can never get a client.

**Comment by matehat** [comment]
If you look at the code, you'll see that the cqerl process is not doing any queries, it's just allocating clients. Its work is very light, when you ask for `cqerl:new_client`, it either gives you one that's already up, or asks pooler to spawn a new one. 

If you end up with that amount of queued messages in the cqerl process, there's a problem with how these client process allocation is done, and has nothing to do with scaling. CQerl does connection pooling and workload distribution across those connection, as much as possible.

Please don't jump to alarmist conclusions based solely on the little information a message queue length gives you.

If you give more context to how you arrived at that situation, I will happily try to find the problem for you.

**Comment by matehat** [comment]
And can you describe the other bottlenecks you found?

**Comment by lpgauth** [comment]
It's not an alarmist conclusion... I've written a lot of high performance Erlang code. 

https://github.com/matehat/cqerl/blob/master/src/cqerl.erl#L272 

That call is not that cheap if I do it 10K/s... you should never have a single point of contention.

The cqerl_cache is another bottleneck, why not make the table public with read_concurrency true? The number of writes is much lower... Also, using re (regex) in there is not the best idea. At least replace it with re2 which has a more linear worst case.

**Comment by matehat** [comment]
`cqerl_cache` [already lets the calling process read from the ETS table directly](https://github.com/matehat/cqerl/blob/16021593c866ca314acd0ba6858194ed44a362b3/src/cqerl_cache.erl#L42-L49) and [is using the `read_concurrency` flag](https://github.com/matehat/cqerl/blob/16021593c866ca314acd0ba6858194ed44a362b3/src/cqerl_cache.erl#L114). Thanks for the `re2` suggestion, I didn't know about it!

As for `cqerl` expensive call, you're right. I'll look into optimize it, and eliminate the single point of contention. If you can think of a better way of handling client allocation, I'd be happy to hear it!

**Comment by lpgauth** [comment]
checkout dispcount - https://github.com/ferd/dispcount

**Comment by lpgauth** [comment]
Also, why block on the client creation? I'd rather receive {error, no_available_clients} fast then have to wait the default 5s gen_server:call/3 timeout...

**Comment by matehat** [comment]
To use that as a sort of back pressure, makes total sense

**Comment by matehat** [comment]
`re2` is now in

**Comment by matehat** [comment]
Man, dispcount is awesome. It'll make cqerl so much more reliable and simpler.

**Comment by matehat** [comment]
I'll port the whole thing to dispcount in a new branch tonight. It'd be cool if you could circle back here and tell me how it improved things with your testing.

**Comment by lpgauth** [comment]
More info on dispcount: http://ferd.ca/rtb-where-erlang-blooms.html

We actually build it for our internal http client, but we use it in other clients (e.g. https://github.com/lpgauth/cassanderl).

I'll probably still write another cassandra client since our needs are pretty extreme, but I'm happy to help you out. If you ever in MTL ping me and let's grab a beer :)

**Comment by matehat** [comment]
Cool, thanks!

If you end up working on a new cassandra client, feel free to rip out the encoding/decoding code from this project. Or better yet, if you wanted improve on this one, I'd happily hand you push access.

As for a beer, sure thing -- I end up in MTL pretty often :)

**Comment by janin** [comment]
@matehat Did you ever get a chance to work on the dispcount branch of cqerl? Or did you run into any unsuspecting problems trying to do it?

**Comment by matehat** [comment]
It turns out to be more complicated than a trivial replace, as both pooling library have somewhat of a different philosophies, but I'm getting on the task of doing the switch now, so stay tuned.

**Comment by bernardd** [comment]
@matehat I was wondering what the status of the dispcount change was. We're striking a couple of problems around the existing pooler implementation (to do with recovery after disconnection) and I'm tempted to rework some bits of the client handling to deal with them. However if the entire thing is going to be changed, soon I'd obviously rather not spend the time :)

**Comment by matehat** [comment]
@bernardd it depends on the sort of solution you were thinking of bringing. If they make cqerl behave better under heavy load then yes, I think it would make sense to work on them and it may obviate the need to bring something like dispcount to the table.

The work I have and had to put on the shelf because of, you know, other work imperatives, is about 50% there about bringing a dispcount-based implementation. That one definitely bring some changes in behavior, specifically regarding failing scenarios and under heavy load, so it would be a breaking upgrade – something like 1.X or 2.X – so I think in any case that your improvements would be useful for whoever wants to keep the current behavior and still have a stable C* client.

**Comment by bernardd** [comment]
@matehat Okay, cool, thanks. Just wanted to make sure the stuff I'm working on wasn't a duplication of effort. Give me a day or two :)

For what it's worth, having done some reading I don't think dispcount is exactly the right tool for the job. It's specifically designed to perform best with systems that are constantly overloaded and while that may apply to some cqerl cases, I strongly doubt it's the "usual" case, even for heavily loaded systems. And in more "normal" cases it's more likely to start dropping stuff that would do just fine if it were briefly queued. There may be exceptions to this, such as the system @lpgauth is dealing with (hi LP!), but if we get cqerl performing decently without bottlenecks, the dispcount-style load shedding can probably be done at an earlier stage. Having said it's not the right tool, however, by stealing a couple of its ideas I think I'm going to be able to remove the single process bottlenecks. More soon.

**Comment by lpgauth** [comment]
@bernardd Hey! If you really care about performance you can checkout my Cassandra client :smile: https://github.com/lpgauth/marina

**Comment by matehat** [comment]
@lpgauth I'd be curious to see some kind of benchmark comparing our two libraries, just so we can a see how big that difference is, and see if it could be useful to port some of your work here if relevant.

**Comment by bernardd** [comment]
@lpgauth Thanks - I'll take a look :)

**Comment by silviucpp** [comment]
Hello guys, 

There are any benchmarks hat we can run to compare cqerl and marina ? I would like to add code to compare with my driver implementation (https://github.com/silviucpp/erlcass) as well. This is a NIF in top of Datastax official C++ client which is fully async. 

If doesn't exist yet I can extend my benchmarks to include this libraries as well.

Silviu

**Comment by bernardd** [comment]
@silviucpp Hi Silviu. None that I'm aware of ouside of the basic load tests in the repo (though @matehat may know some) - I'd be thrilled if you were able to provide some more.

**Comment by lpgauth** [comment]
I've done some benchmarks with `basho_bench` but it's not perfect. Best benchmark so far for me is to actually try it in production 😄

**Comment by silviucpp** [comment]
We are using erlcass in production and performs very nice under high load. At the begin we used cqerl but we had different issues one of being: 

https://github.com/matehat/cqerl/issues/50

**Comment by matehat** [comment]
@silviucpp since your last comment, #50 was fixed with #91. I'd be curious to know about the other issues you had.

**Comment by silviucpp** [comment]
@matehat  I didn't tested any longer your library in the last time but another issue was related to the poor performances during load tests at that point. This was one of the main reason that forced me to write an Erlang bidding for the datastax official c++ client.

Will be interesting to make a script to load test erlcass, cqerl and marina and to compare the results. 
Unfortunately I don't have time at this moment to do this but if anyone else has will be interesting. 

Silviu

**Comment by matehat** [comment]
@silviucpp cool, thanks!

**Comment by matehat** [comment]
Added #96 to track the addition of a benchmark suite. Closing, as there isn't much more we can do at this point.
