### ISSUE TITLE
Excessive records in ETS table that caches prepared queries?

### ISSUE THREAD

**Issue by bokner** [matehat/cqerl#50]
Hello,

Currently cqerl_cached_queries (ETS table that caches queries) has {pid(), statement()} key. This leads to having multiple records per statement, more specifically, every pool connection creates a record for the statement it calls. This seems excessive, as logically the cache table only needs a single entry per statement to decide if it has already been prepared. It's also a housekeeping problem, as the records don't get removed as the pool process dies for any reason. I don't see any usage for PID part of the key in the code, unless I'm missing something. I've made changes to use statement only as a key, and haven't encounter any problems so far. 

Please advise. If removing PID from the key sounds like a good idea, I'll submit a pull request for this.

Best regards,
Boris

**Comment by matehat** [comment]
Sorry for the long response. The reason the PID is included in there is that Cassandra nodes prepare statements on specific nodes, so if a second client connects to second Cassandra node, the prepared statements are not going to be the same as those the first client. Moreover, if a Cassandra node dies, clients connected to it will also die, and so new clients will forcibly talk to a new Cassandra node, which doesn't have any prepared statements.

But I agree there should be a garbage collection mechanism in place, and we could improve the caching mechanism to be more sophisticated, as there are still a lot less clients than there are different cassandra nodes.

**Comment by matehat** [comment]
Created another issue to track the cache housekeeping task
