### ISSUE TITLE
uuid:get_v1 has changed to support Erlang 18

### ISSUE THREAD

**Issue by makrisoft** [matehat/cqerl#51]
Hi,

uuid master has a backwards incompatible change:
https://github.com/okeuday/uuid/commit/04a3037c492d2331dd7193c465868c1d71b28363

in cqerl_datatypes (line 257):
change:
encode_data({timeuuid, now}, _Query) ->
    uuid:get_v1(uuid:new(self(), os));

To:
encode_data({timeuuid, now}, _Query) ->
    {Id, _} = uuid:get_v1(uuid:new(self(), os)),
    Id;

Thanks
Ernie

**Comment by matehat** [comment]
Could you make a pull request implementing the changes and making sure it stays backward compatible?

**Comment by makrisoft** [comment]
I can, but a better approach might be to peg the uuid dep to a tag rather than master. That way, we can target the api properly. How does that sound?

**Comment by matehat** [comment]
Sounds good :smile:

**Comment by matehat** [comment]
This is now merged in master, as of 140cb85a91a559063d054179b5c5ccfbe6e57c6d
