### ISSUE TITLE
Type specs are incorrect for run_query

### ISSUE THREAD

**Issue by chwevans** [matehat/cqerl#55]
The type spec for run_query suggests its result is ```#cql_result{}```, however it actually returns ```{ok, #cql_result{}} | {error, error()} | {ok, void}``` where ```error()``` seems to be ```{pos_integer(), binary(), term()}```.

**Comment by matehat** [comment]
I think you're right. Can you make that a pull request? :smile:

**Comment by chwevans** [comment]
No problem, https://github.com/matehat/cqerl/pull/56
