### ISSUE TITLE
Newer data types of cassandra 2.2 not supported

### ISSUE THREAD

**Issue by kmittal01** [matehat/cqerl#57]
The newer data types of Cassandra 2.2 like **tinyint are not supported** and an error is received while trying to select a column which is tinyint (not tested with other newer data types like date, smallint etc. ).

**Comment by matehat** [comment]
Thanks for reporting!

**Comment by matehat** [comment]
Sorry for taking so long to get to this. I'll get on this now. Thanks again.

**Comment by matehat** [comment]
All the datatypes you asked for are merged in master, not yet in a release

**Comment by kmittal01** [comment]
Thanks!!
