### ISSUE TITLE
We may need a way to allow cqerl to support multiple clusters

### ISSUE THREAD

**Issue by leiyangyou** [matehat/cqerl#59]

**Comment by matehat** [comment]
I'm not sure I understand the title

**Comment by leiyangyou** [comment]
Sorry, let me explain this a bit more,

Im not yet aware of a way of configuring cqerl to address the need where an app needs to connect to multiple separate clusters of cassandra with pooling

I believe pooling only works with one cluster at the moment?

**Comment by matehat** [comment]
Sorry for taking that long to answer, I didn't see your reply .. you are right that it does not and that it's a major flaw. Do you think you'd like to tackle that (or if you already did) or should I get started on this?

**Comment by matehat** [comment]
This is now in, see the updated [readme.md](/matehat/cqerl/#clusters)
