### ISSUE TITLE
Can't insert negative decimals or decimals of certain size using cql_query 

### ISSUE THREAD

**Issue by trarbr** [matehat/cqerl#60]
We're doing a project for collecting and storing sensor data using Elixir (1.1.1) and Cassandra (2.1.11). We''re using cqerl (0.8.0) to talk to Cassandra, but have noticed a problem with the decimal type. In short, if using the cql_query record to define a query, it fails when inserting negative decimals, and inserts a wrong number if the decimal has a certain size (e.g. trying to insert {10357780, 0} will store -6419436 in Cassandra).

Assume a simple table like this:

```
CREATE TABLE tests.decimals (id INT PRIMARY KEY, value DECIMAL);
```

If I use a simple query string to insert data like this, it works:

```
{:ok, client} = :cqerl.new_client
{:ok, result} = :cqerl.run_query(client, "INSERT INTO tests.decimals (id, value) VALUES (10, -10.0);")
{:ok, result} = :cqerl.run_query(client, "INSERT INTO tests.decimals (id, value) VALUES (10, 10357780);")
```

But if I try to use cql_query, inserting a negative number will fail:

```
query = cql_query(statement: "INSERT INTO tests.decimals (id, value) VALUES (11, ?);", values: [value: {-10, 0}])
{:ok, client} = :cqerl.new_client
{:ok, result} = :cqerl.run_query(c, query)
```
That throws the following error: 

``` 
[error] Process #PID<0.309.0> raised an exception
** (ArithmeticError) bad argument in arithmetic expression
    (stdlib) :math.log(-10)
    (cqerl) src/cqerl_datatypes.erl:342: :cqerl_datatypes.encode_data/2
    (cqerl) src/cqerl_datatypes.erl:314: :cqerl_datatypes.encode_data/2
    (stdlib) lists.erl:1238: :lists.map/2
    (cqerl) src/cqerl_processor.erl:67: :cqerl_processor.process/3
```

Fixing this is pretty trivial, we just need to call `abs/1` on `Val` before calling `math.log`: https://github.com/trarbr/cqerl/commit/a171272c7cf528c94f0e835f21952c824571c10a

However, for numbers of a certain size (positive or negative) it will some times store the wrong number. (maybe the byte count is wrong?). E.g: 

```
query = cql_query(statement: "INSERT INTO tests.decimals (id, value) VALUES (11, ?);", values: [value: {10357780, 0}])
{:ok, client} = :cqerl.new_client
{:ok, result} = :cqerl.run_query(c, query)
```

This will store -6419436 in Cassandra instead of 10357780.

Fixing the issue with negative numbers was pretty easy, but I don't know how to fix the other issue.

**Comment by matehat** [comment]
Sorry for taking so long to get to this, I've been pretty busy.

Good news is, I now got financial support to put more work on this project, so this will get fixed ASAP, as our company will need it fixed too. Stay tuned

**Comment by trarbr** [comment]
That's great news! :+1: I had a look at alternatives to cqerl, but were not really impressed with what I could find. The best bet seemed to be erlcass (https://github.com/silviucpp/erlcass). On one hand I like that it uses the DataStax C++ driver for performance and maturity - on the other hand, I don't like using NIFs. cqerl also seems more feature rich (we need pagination, which is not in erlcass).

Anyway, we went with doubles instead of decimals for this project, but we might want to use decimals for future projects.

**Comment by matehat** [comment]
Thanks for the kind words! BTW, I also just started out a Elixir project to make it easier for Elixir developers to talk to cassandra: https://github.com/matehat/cqex

I'm almost finished with implementing the latest cassandra protocol, including time, date, tinyint, smallint, user-defined and tuple types. Decimal and varints are a completely different beast though, and that's the only thing left for a rather complete implementation!

**Comment by matehat** [comment]
Oh, and cqerl now supports maps! :wink:

**Comment by bernardd** [comment]
I would imagine that the PR I just opened (https://github.com/matehat/cqerl/pull/80) should correct this, since the `decimal` type internally uses `varint` encoding which was broken in basically the way I described.

**Comment by bernardd** [comment]
This should now be working.
