### ISSUE TITLE
Doesn't work with cassandra 3.0.2

### ISSUE THREAD

**Issue by kmittal01** [matehat/cqerl#66]
When I try to create a new client in cassandra 3.0.2 using the following:

    {:ok, client} = :cqerl.new_client({})

It gives the follwoing error:

* (exit) exited in: :gen_server.call(:cqerl, {:get_client, {{127, 0, 0, 1}, 9042}, []})
    ** (EXIT) time out
    (stdlib) gen_server.erl:182: :gen_server.call/2

However, this works fine in cassandra 2.2.4

**Comment by matehat** [comment]
I just tried it with a 3.0.2 cassandra instance and it works fine. Can you provide more information about your setup and the issue you're having?
