### ISSUE TITLE
{:ok, client} = :cqerl.new_client({"52.**.***.*",9042})  - this format doesn't work

### ISSUE THREAD

**Issue by kmittal01** [matehat/cqerl#76]
I have tested the following two lines of code on elixir shell (iex):

`{:ok, client} = :cqerl.new_client({"52.**.***.*",9042}) #Doesn't work`
`{:ok, client} = :cqerl.new_client({{52,**,***,*},9042}) : #Works`

The environment that I am using is the following:
Elixir 1.0.5
OTP 17
Server is on AWS and I used the following configuration to make cassandra available from remote servers:
- Comment rpc_address
- Uncomment rpc_interface [rpc_interface: eth0]
- Uncomment rpc_interface_prefer_ipv6: false
- Enable thrift using nodetool [nodetool enablethrift]

After the above configuration, I was not able to connect using default configuration, so:
`{:ok, client} = :cqerl.new_client({})`
 command started giving:
`no match of right hand side value: {:error, :no_available_clients}`

So, I tried connecting using the public IP address of the server, but for some reason the first command didn't work and gave the following error:
`{:ok, client} = :cqerl.new_client({"52.**.***.*",9042})`
```

** (FunctionClauseError) no function clause matching in :cqerl.prepare_node_info/1
    (cqerl) src/cqerl.erl:599: :cqerl.prepare_node_info({"52.35.128.1", 9042})
    (cqerl) src/cqerl.erl:102: :cqerl.new_client/2
```

**Comment by kmittal01** [comment]
Issue was on on older version of cqerl. No such issue with the latest version.

**Comment by matehat** [comment]
Thanks for investigating!
