### ISSUE TITLE
Binding fields with multiple conditions

### ISSUE THREAD

**Issue by bernardd** [matehat/cqerl#78]
My apologies if this feature already exists - I've been through the docs and the code and couldn't see how to do it.

For the query:

`SELECT * FROM table WHERE time < ? AND time > ?`

The `time` field is used twice with different values. Is there any way to specify the two different values in the `cqerl_query.values` list/map we pass into `cqerl:run_query()`? Or are we currently limited to just hardcoding those values into the query statement (presumably meaning the query can't be cached)?

**Comment by matehat** [comment]
Just added an example in the readme file for this sort of case: 59ab3f76934ca4a19f605d7d1d5f4bba6015db03

So, using that, you could write your statement as:

```erlang
#cql_query{
  statement="SELECT * FROM table WHERE time < :lower AND time > :upper",
  values=[
    {lower, SomeValue},
    {upper, SomeOtherValue}
  ]
}
```

**Comment by bernardd** [comment]
Ah, brilliant, thanks very much.
