### ISSUE TITLE
0.9.0 error conditions

### ISSUE THREAD

**Issue by matehat** [matehat/cqerl#79]
@bernardd

I don't know if I'm missing something, but the pull request you had open does not make any test pass. The very first task of `create_keyspace` fails repeatedly with thousands of

```erlang
*** System report during integrity_SUITE:create_keyspace/1 in initial 2016-02-13 20:14:21.021 ***

=SUPERVISOR REPORT==== 13-Feb-2016::20:14:21 ===
     Supervisor: {local,pooler_g2gDaARhf2EAYQBhAWIAACNSZAAVYW5vdGhlcl9mYWtlX2tleXNwYWNl_member_sup}
     Context:    child_terminated
     Reason:     {server_error,8704,
                               <<"Keyspace 'another_fake_keyspace' does not exist">>}
     Offender:   [{pid,<0.2751.0>},
                  {id,cqerl_client},
                  {mfargs,{cqerl_client,start_link,undefined}},
                  {restart_type,temporary},
                  {shutdown,brutal_kill},
                  {child_type,worker}]
```

Were the tests in the pull request, in a passing state?

**Comment by bernardd** [comment]
Odd. The branch from which I generated it certainly passes fine on my machine:

```
$ make test
./rebar skip_deps=true ct
==> cqerl (ct)
DONE.
eaddrinuse}}Testing src.cqerl: TEST COMPLETE, 18 ok, 0 failed of 18 test cases
```
(Not sure what that `eaddrinuse}}` bit is about, but I'm just looking at the `18 ok` bit :) )
Which of course isn't to say that it isn't breaking for you, but yeah, it's definitely in a "passing" state for me.

**Comment by bernardd** [comment]
I also just checked out the current master branch prior to the reversion of the merge:

```
[(detached from 39772d2)] $ make test
./rebar skip_deps=true ct
==> cqerl (ct)
DONE.
    eaddrinuse}}Testing src.cqerl: TEST COMPLETE, 18 ok, 0 failed of 18 test cases
```

So it looks like there's some kind of weird difference between your system and mine. Could it be the version of Cassandra we're running? I'm testing against 3.0.2.

**Comment by matehat** [comment]
Thanks for following up. Which version of Erlang are you running?

**Comment by bernardd** [comment]
18.2 from the ESL repository. (On Linux Mint 17.3 which is an Ubuntu Trusty derivative, just in case it matters).

**Comment by matehat** [comment]
Hmm, really weird. I deleted the directory, cloned it again from scratch and now all tests pass :smile:

**Comment by bernardd** [comment]
Hooray! Rebar has something of a habit of leaving around stale files that can mess things up. I tend to do a `git clean -dfx` whenever I switch branches, especially if I'm seeing weirdness.

**Comment by matehat** [comment]
Good tip :smile:
