### ISSUE TITLE
timeout to get connection

### ISSUE THREAD

**Issue by lealoureiro** [matehat/cqerl#84]
Hi,

I'm using cqerl from branch master with Erlang 18.3 and getting a timeout when i'm trying to get connection from pool:

11:15:25.303 [error] Ranch listener http terminated with reason: [{reason,{timeout,{gen_server,call,[cqerl,get_any_client]}}},{mfa,{auth_handler,handle,2}},{stacktrace,[{gen_server,call,2,[{file,"gen_server.erl"},{line,204}]},{auth_library,get_user_id,1,[{file,"src/auth_library.erl"},{line,44}]},{auth_library,login,2,[{file,"src/auth_library.erl"},{line,24}]},{auth_handler,login,3,[{file,"src/auth_handler.erl"},{line,57}]},{auth_handler,handle,2,[{file,"src/auth_handler.erl"},{line,26}]},{cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,...}]},...]},...]

Any clue?

**Comment by lealoureiro** [comment]
I was working Cassandra 2.1.12, i've updated to 2.2.5 and now is working.

**Comment by bernardd** [comment]
I would surmise, then, that this is probably down to https://github.com/matehat/cqerl/issues/63.

**Comment by hopewise** [comment]
Can anyone help here: https://github.com/matehat/cqex/issues/9
