### ISSUE TITLE
For millions of connected users how to connect to a random node?

### ISSUE THREAD

**Issue by alfredbaudisch** [matehat/cqerl#89]
I want to write an ejabberd Cassandra module to store (and retrieve) millions of messages that are exchanged daily. Initially my Cassandra cluster will have 8 nodes, but I'm still not sure on how to integrate cqerl to use random nodes for each read/write operation.

In ejabberd each client connection is a process. Should I have a `Client = cqerl:new_client()` in every process and use the process' `Client` to do operations in this process or should I have an application wide `Client` and then just call it in each process?

What is the right cqerl approach for possible millions of writes per minute, balancing the calls between all nodes?

**Comment by bernardd** [comment]
As luck would have it, I'm just finalising a change now that might help you out (especially since I wrote it for an ejabberd-based application). See #88 for details - should be in in the next couple of days. The catch is that there's currently no automatic node selection/distribution - as things stand you have to do that yourself - maybe just have each process randomly pick a node when they first start up. Or you could add that feature to the library :) I'm probably going to have to add something like that sooner or later anyway, but not right now.

**Comment by matehat** [comment]
@alfredbaudisch The change is in!

**Comment by alfredbaudisch** [comment]
@bernardd @matehat thank you! Unfortunately I'm having a hard time trying to integrate with ejabberd (not because of ejabberd, but because I still didn't grasp cqerl usage). 

When using the `hash` mode, shouldn't I be able to call `cqerl:get_client/2` in every client's process?

**Comment by matehat** [comment]
You should, but you'll have to specify which of the node you want to talk to as the first argument. You can build a custom and private selection mechanism to do that part, or build it inside cqerl and make a pull request (:+1:), or even wait for us to do that part.

In `pooler` mode, you can use `cqerl:new_client/0`, given you have proper application config in place, and that would randomly select one of the configured nodes.

**Comment by matehat** [comment]
i.e. Once you get a client using `cqerl:get_client/2`, the database node you're talking to will always be the same using that client.

**Comment by alfredbaudisch** [comment]
Thank you @matehat but I'm sorry I'm still not sure I'm doing it right. 

For EVERY message sent to ejabberd I'm doing this on the store function (hand coded data as example):

	Hosts = [ { "192.168.99.100", 7771 }, { "192.168.99.100", 7772 }, { "192.168.99.100", 7773 } ],
	Index = random:uniform(length(Hosts)),

	{ok, Client} = cqerl:new_client(lists:nth(Index,Hosts), [
		{keyspace, "ejabberd"}
	]),
	cqerl:run_query(Client, #cql_query{
		statement = "INSERT INTO messages(id, message) VALUES(?, ?);",
		values = [{id, TS}, {message, Body}]
	}),
	cqerl:close_client(Client),

This is working, but I feel that something is wrong, like opening and closing the connection for EVERY message sent? Is this the right approach?

Also, I'm using `cqerl:new_client` because I didn't manage to get `cqerl:get_client` working here at all.

And of course I am starting cqerl and adding to the ejabberd supervisor:

    ejabberd:start_app(cqerl),
    Supervisor_name = gen_mod:get_module_proc(Host, cqerl_sup),
    ChildSpec = {Supervisor_name,
		 {cqerl_sup, start_link, [Host]}, transient,
		 infinity, supervisor, [cqerl_sup]},
    supervisor:start_child(ejabberd_sup, ChildSpec),

**Comment by matehat** [comment]
It is the right way, and no, the connection is not open and closed for every request. Connections are open the first time they are used and maintained open for the next client(s) to reuse quickly.

I'd be curious to know what went wrong when you tried using `get_client/2` though

**Comment by matehat** [comment]
Agreed about example project, I'll try to find the time to make something up.

**Comment by alfredbaudisch** [comment]
Regarding `get_client/2`, I followed the docs and your tips, but I get this:

`	00:13:37.848 [error] {badarg,[{ets,lookup,[cqerl_client_tables,{{"192.168.99.100",7772},[{keyspace,ejabberd}]}],[]},{cqerl_hash,get_table,1,[{file,"src/cqerl_hash.erl"},{line,194}]},{cqerl_hash,get_client,1,[{file,"src/cqerl_hash.erl"},{line,178}]},{mod_mam,store,8,[{file,"src/mod_mam.erl"},{line,796}]},{mod_mam,user_send_packet,4,[{file,"src/mod_mam.erl"},{line,242}]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},{ejabberd_hooks,run_fold1,4,[{file,"src/ejabberd_hooks.erl"},{line,365}]},{ejabberd_c2s,session_established2,2,[{file,"src/ejabberd_c2s.erl"},{line,1268}]}]}`

**Comment by bernardd** [comment]
Either you haven't started the `cqerl` application, or you haven't started it with the `{mode, hash}` environment variable set.

**Comment by alfredbaudisch** [comment]
@bernardd I'm running ejabberd in an Elixir project and the project doesn't read `app.config` but instead `config/config.exs`

    config :cqerl,
        mode: :hash

That solved it, I had completely ignored this detail until now.

**Comment by matehat** [comment]
Closing for now, but feel free to reopen if you think something is wrong

**Comment by alfredbaudisch** [comment]
@bernardd @matehat maybe not the best place to ask, but I didn't find on Google any other way to contact you guys: any of you (or both) would be available for paid consulting for the library implementation, Erlang and Cassandra in general? If so, please contact me at alfred@fredapp.com.br.
