### ISSUE TITLE
how to call cqerl from ejabberd

### ISSUE THREAD

**Issue by jahabersadhik** [matehat/cqerl#95]
First of thank for your wonderful module developed. i have some question. do you have any idea how to call cqerl from ejabberd server.

**Comment by bernardd** [comment]
The same way you call it from anything else. Is there a specific problem you're having?

**Comment by jahabersadhik** [comment]
No.

**Comment by matehat** [comment]
Thanks for the interest and for the kind words @jahabersadhik! If you want to see examples of how to use the library, have a close look at the Readme file at the root of this project.
