### ISSUE TITLE
Cannot build dependency by rebar

### ISSUE THREAD

**Issue by szymon-wlodarczyk** [matehat/cqerl#99]
After I add cqerl in rebar.config in my project I am not able to build dependency.
I have following error:
```
../deps/cqerl/include/cqerl.hrl:61: type map() undefined
```

I have same result for master branch and v1.0 tag.

Regards,
Szymon

**Comment by szymon-wlodarczyk** [comment]
I am using E16B03

**Comment by szymon-wlodarczyk** [comment]
Probably you meant maps:map() there?

**Comment by bernardd** [comment]
Actually the correct type is `map()`. The problem you're hitting is that maps don't exist in R16. There's code to work around this in most places, but evidently that bit was missed. Probably the simplest workaround for your case is just to define `map()` to be something innocuous. Unfortunately Erlang lacks version macros or something similar that might make this easy to `ifdef` our way around.

**Comment by szymon-wlodarczyk** [comment]
Yes, you are right here.
I will do as you suggest.
